# Convolutional Neural Network (CNN) in Keras

 Convolutional neural network (CNN) can be used to clasify images . 

Computers see images as pixels. Pixels in images are usually related. For example, a certain group of pixels may signify an edge in an image or some other pattern. Convolutions use this to help identify images.
A convolution multiplies a matrix of pixels with a filter matrix or ‘kernel’ and sums up the multiplication values. Then the convolution slides over to the next pixel and repeats the same process until all the image pixels have been covered.

## 1. Loading the dataset

The mnist dataset is provided as part of the Keras library
This dataset consists of 70,000 images of handwritten digits from 0–9.CNN model will classify them.
Out of the 70,000 images provided in the dataset, 60,000 are given for training and 10,000 are given for testing.
When we load the dataset below, X_train and X_test will contain the images, and y_train and y_test will contain the digits that those images represent.

In [1]:
from keras.datasets import mnist
#download mnist data and split into train and test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()

Using TensorFlow backend.


11493376/11490434 [==============================] - 1s 0us/step


In [6]:
X_train.shape

(60000, 28, 28)

In [7]:
y_train.shape

(60000,)

In [8]:
X_test.shape

(10000, 28, 28)

In [9]:
y_test.shape

(10000,)

In [3]:
## Each image is a 28 * 28 numpy array
X_train[444].shape

(28, 28)

In [11]:
## Let's look at one of the images
import matplotlib.pyplot as plt
print(y_train[444])
plt.imshow(X_train[444]);

2


In [27]:
plt.figure(figsize=(10,10))
for i in range(25):
    plt.subplot(5,5,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(X_train[i])
    # The CIFAR labels happen to be arrays, 
    # which is why you need the extra index
plt.show()

## 2. Data pre-processing

Next, we need to reshape our dataset inputs (X_train and X_test) to the shape that our model expects when we train the model. The first number is the number of images (60,000 for X_train and 10,000 for X_test). Then comes the shape of each image (28x28). The last number is 1, which signifies that the images are greyscale.

In [12]:
from keras.utils import to_categorical
#one-hot encode target column
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [20]:
#reshape data to fit model
X_train = X_train.reshape(60000,28,28,1)
X_test = X_test.reshape(10000,28,28,1)

## 3.Building the model

In [21]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten
from keras.layers import Dense, Dropout, Activation, Flatten
#create model
model = Sequential()
#add model layers
model.add(Conv2D(64, kernel_size=3, input_shape=(28,28,1)))
model.add(Activation('relu'))
model.add(Conv2D(32, kernel_size=3))
model.add(Activation('relu'))
model.add(Flatten())
model.add(Dense(10))
model.add(Activation('softmax'))

In [22]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_4 (Conv2D)            (None, 26, 26, 64)        640       
_________________________________________________________________
activation_4 (Activation)    (None, 26, 26, 64)        0         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 24, 24, 32)        18464     
_________________________________________________________________
activation_5 (Activation)    (None, 24, 24, 32)        0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 18432)             0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                184330    
_________________________________________________________________
activation_6 (Activation)    (None, 10)               

Sequential is the easiest way to build a model in Keras. It allows you to build a model layer by layer.
We use the ‘add()’ function to add layers to our model.
Our first 2 layers are Conv2D layers. These are convolution layers that will deal with our input images, which are seen as 2-dimensional matrices.
64 is first layer depth and 32 is second layer depth. 
Kernel size is the size of the filter matrix for our convolution. So a kernel size of 3 means we will have a 3x3 filter matrix.
Activation is the activation function for the layer. The activation function we will be using for our first 2 layers is the ReLU, or Rectified Linear Activation.
In between the Conv2D layers and the dense layer, there is a ‘Flatten’ layer. Flatten serves as a connection between the convolution and dense layers.
‘Dense’ is the layer type we will use in for our output layer. Dense is a standard layer type that is used in many cases for neural networks.
We will have 10 nodes in our output layer, one for each possible outcome (0–9).
The activation is ‘softmax’. Softmax makes the output sum up to 1 so the output can be interpreted as probabilities. The model will then make its prediction based on which option has the highest probability.


## 3 .Compiling the model


Compiling the model takes three parameters: optimizer, loss and metrics.
The optimizer controls the learning rate. We will be using ‘adam’ as our optmizer. The adam optimizer adjusts the learning rate throughout training.

We will use ‘categorical_crossentropy’ for our loss function. This is the most common choice for classification. 
To make things even easier to interpret, we will use the ‘accuracy’ metric to see the accuracy score on the validation set when we train the model.

In [23]:
#compile model using accuracy to measure model performance
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

## 4.Training Model

To train, we will use the ‘fit()’ function on our model with the following parameters: training data (train_X), target data (train_y), validation data, and the number of epochs.
For our validation data, we will use the test set provided to us in our dataset, which we have split into X_test and y_test.
The number of epochs is the number of times the model will cycle through the data. The more epochs we run, the more the model will improve, up to a certain point. After that point, the model will stop improving during each epoch. For our model, we will set the number of epochs to 3.

In [24]:
#train the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=3)

Train on 60000 samples, validate on 10000 samples
Epoch 1/3
60000/60000 [==============================] - 52s 862us/step - loss: 0.2311 - accuracy: 0.9537 - val_loss: 0.0809 - val_accuracy: 0.9775
Epoch 2/3
60000/60000 [==============================] - 52s 863us/step - loss: 0.0659 - accuracy: 0.9793 - val_loss: 0.0810 - val_accuracy: 0.9753
Epoch 3/3
60000/60000 [==============================] - 52s 862us/step - loss: 0.0462 - accuracy: 0.9851 - val_loss: 0.0986 - val_accuracy: 0.9761


## 5.Using our model to make predictions
If you want to see the actual predictions that our model has made for the test data, we can use the predict function. The predict function will give an array with 10 numbers. These numbers are the probabilities that the input image represents each digit (0–9). The array index with the highest number represents the model prediction. The sum of each array equals 1 (since each number is a probability).
To show this, we will show the predictions for the first 4 images in the test set.
Note: If we have new data, we can input our new data into the predict function to see the predictions our model makes on the new data. Since we don’t have any new unseen data, we will show predictions using the test set for now.


In [25]:
#predict first 4 images in the test set
model.predict(X_test[:4])

array([[4.8987142e-10, 3.2429109e-16, 4.3767381e-10, 8.5497973e-09,
        1.5664456e-14, 9.4998781e-13, 1.8619057e-16, 1.0000000e+00,
        1.2398357e-12, 3.4582870e-09],
       [2.3017732e-09, 3.3684906e-09, 9.9935120e-01, 2.2786622e-08,
        1.4840863e-12, 9.0220002e-12, 6.4856221e-04, 4.3616661e-15,
        2.3027154e-07, 1.5747467e-13],
       [1.2208086e-09, 9.9999404e-01, 1.6952352e-07, 1.8874551e-10,
        2.5919248e-06, 1.8543851e-08, 8.5731514e-08, 5.6689413e-07,
        2.4916217e-06, 1.1496391e-11],
       [9.9999917e-01, 2.8696737e-15, 9.6093922e-10, 2.5888851e-17,
        1.5392173e-14, 7.5955333e-15, 8.8087398e-07, 1.6991576e-13,
        3.7151362e-11, 4.1051926e-09]], dtype=float32)

In [26]:
#actual results for first 4 images in test set
y_test[:4]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)